### PR TITLE
Add build instructions for OS X

### PR DESCRIPTION
**Pull request by phrohdoh**
I've added some build instructions that depend on [homebrew](http://brew.sh).
Is there an IRC channel for this project?

### CODE REVIEW

**Comment by EggsSeriously** [comment]
I don't think so, but maybe we can make it happen?

**Comment by phrohdoh** [comment]
I'm all for #openaoe on freenode fwiw.

**Comment by EggsSeriously** [comment]
Hey why not, I'll go get a good client.

**Comment by angered-ghandi** [comment]
Awesome. Thanks!

**Pull request merged**
