### PR TITLE
Adding install GCC (linux) to readme

### PR DESCRIPTION
**Pull request by EggsSeriously**
In the event the user doesn't have GCC installed on linux. To the best of my knowledge most distros don't come packaged with it?

### CODE REVIEW

**Comment by phrohdoh** [comment]
You've listed `base-devel` twice in a way that would imply the two OSes need different packages.
Is this intentional?

**Comment by EggsSeriously** [comment]
darn it, that should have been build-essential for ubuntu/debian!

**Comment by phrohdoh** [comment]
These commits should be squashed IMO.
Let's hear from @angered-ghandi on that though.

**Comment by angered-ghandi** [comment]
Looks good. I'll merge it in squashed. Thanks!

**Pull request merged**
